### ISSUE TITLE
Getting exception when add it to android studio 2.1.3

### ISSUE THREAD

**Issue by pratikshah563** [lp0/slf4j-android#7]
i getting Exception as below:
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/slf4j/impl/StaticLoggerBinder;

I am Using Android studio 2.1.3 and java 8

**Comment by lp0** [comment]
You have another dependency that includes ```org.slf4j.impl.StaticLoggerBinder```, you'll have to remove it as you can't have two logging implementations.
