### ISSUE TITLE
README.md references Maven Central version that does not exist

### ISSUE THREAD

**Issue by bjohnso5** [lp0/slf4j-android#8]
The usage instructions reference version 1.7.25-0 on Maven Central, which does not exist. The most recent version available is 1.7.22-0 (http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22eu.lp0.slf4j%22%20AND%20a%3A%22slf4j-android%22).

Looking at the most recent commit, I assume it was a find and replace mistake.

**Comment by lp0** [comment]
I'm not sure why you'd think it was a mistake when the pom.xml file was also updated.

That version is now available on Maven Central.
